# Main config file for icon theme.
theme = "hugo-assembly"
baseURL = "https://www.example.com/"
languageCode = "en-US"
title = "My Hugo Config"

# Metadata
[params]
  author = "Salomon Valverde"
  description = "Cool description"

# banner section (from here on is for assembly theme)
[params.banner]
  title = "MobiClaim!"
  byline = "Reclaim your devices faster and safer with us"

[params.actions] # CTAs
  enable = true
  register = "Recover your Phone!"

# Navigation section
[params.nav]
  home = "Welcome"
  services = "What we Do"
  team = "About Us"
  contact = "Contact Us"

# Services section
[params.services]
  enable = true
  title = "Header title for services"
  subtitle = "subtitle for services"

  # [params.services.images]
  #   enable = true

  #   [[params.services.images.list]]
  #     img = "images/img_3.jpg"
  #   [[params.services.images.list]]
  #     img = "images/img_2.jpg"
  #   [[params.services.images.list]]
  #     img = "images/img_1.jpg"

  # 4 column
  [[params.services.item]]
    weight = 1
    description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repudiandae aliquid aperiam eveniet officia molestiae temporibus beatae dolores dignissimos"
    button_item_info = "Learn more"

  [[params.services.item]]
    weight = 2
    description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla explicabo, molestiae eaque fugiat dolores est esse, doloremque placeat assumenda corrupti officia dolorum."
    button_item_info = "Locate Phone"

  [[params.services.item]]
    weight = 3
    description = "Possimus id dicta consequuntur veritatis, reiciendis at expedita voluptate sint distinctio eligendi!"
    button_item_info = "My Bounty"

  [[params.services.item]]
    weight = 4
    description = "Possimus id dicta consequuntur veritatis, reiciendis at expedita voluptate sint distinctio eligendi!"
    button_item_info = "My Bounty"

# Team section
[params.team]
  enable = true
#   title = "About the Team"
#   description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

#   [[params.team.item]]
#     name = "Jean Doe"
#     position = "Chief legend"
#     description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
#     img = "images/person1.jpg"
#     facebook = "#"
#     twitter = "#"
#     dribbble = "#"
#     instagram = "#"
#     github = "#"
#     linkedin = "#"

#   [[params.team.item]]
#     name = "Alice Doe"
#     position = "Chief overlord"
#     description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
#     img = "images/person2.jpg"
#     facebook = "#"
#     twitter = "#"
#     dribbble = "#"
#     instagram = "#"
#     github = "#"

#   [[params.team.item]]
#     name = "John Doe"
#     position = "Chief haranguer"
#     description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
#     img = "images/person3.jpg"
#     facebook = "#"
#     twitter = "#"
#     dribbble = "#"
#     instagram = "#"
#     github = "#"

# Contact section
[params.contact]
  enable = true
#   title = "Get In Touch"
#   message = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
#   name_placeholder = "Your name"
#   email_placeholder = "Your email"
#   email_disclaimer = "We'll never share your email with anyone else."
#   message_placeholder = "Please enter a message."
#   button_text = "Submit"

# Footer section
[params.footer]
  enable = true
  copy = "&copy; MobiClaim! All rights reserved. | Photos by <a href=\"http://fotogrph.com/\">Fotogrph</a> | Design by <a href=\"http://templated.co\" rel=\"nofollow\">TEMPLATED</a>."
  twitter = "#"
  facebook = "#"
  instagram = "#"

